### ISSUE TITLE
有没有想法在汉字转拼音的功能里加一些格式化的选项？

### ISSUE THREAD

**Issue by HumJ0218** [stulzq/ToolGood.Words.Core#1]
比如
分隔？pinyin、pin yin，或者输出成数组让用户自己决定分隔
大小写？pin yin、Pin Yin、PIN YIN
是否带有声调符号？pīn yīn
ü的样式？吕：lv、lü、lyu

**Comment by stulzq** [comment]
本项目不再维护，请大家支持原项目。

https://github.com/toolgood/ToolGood.Words
